### ISSUE TITLE
Imported file path error

### ISSUE THREAD

**Issue by OnlyKoei** [Live2D/CubismCocosCreatorComponents#1]
You need to change the pathname of the import.
![image](https://user-images.githubusercontent.com/40415168/205560119-0c787df2-1c44-455b-9c35-dcb7d17662ff.png)
![image](https://user-images.githubusercontent.com/40415168/205560299-e4c73310-b905-4579-b109-054f39c4357b.png)
![image](https://user-images.githubusercontent.com/40415168/205560518-84fccc37-abcf-4931-9ffd-1efef79cec92.png)

**Comment by wada-at-live2d-com** [comment]
@OnlyKoei 
Thank you for reporting the issue.

This is considered a common path error.
I will fix it immediately and merge it into the develop branch.
Please wait a moment.

**Comment by wada-at-live2d-com** [comment]
@OnlyKoei 
We have merged the PR with the corrected directory name error you pointed out.
Please check.
